### PR TITLE
Adding Docker option

### PR DESCRIPTION
**Pull request by m4n3dw0lf**

### CODE REVIEW

**Comment by kingthorin** [comment]
Nice work!

**Comment by GrigoriyLyullin** [comment]
Hello @m4n3dw0lf @kingthorin 

I tried to use Docker feature but it does not work for me. It seems that it somehow connected to mysql version.

I've checked the repo and just executed "docker-compose up", then 
http://localhost:8080/JavaVulnerableLab/Install and click the Install Button, I've got following error in console log:

`
javavulnlab_1  | SQLException: Could not create connection to database server.
javavulnlab_1  | SQLState: 08001
javavulnlab_1  | VendorError: 0
`
and following message on web UI: "Something went wrong. Unable to install"

So I've changed mine docker-compose.yml from "image: mysql" to "image: mysql:5.7" and it works for me.

Could it be connected to new caching_sha2_password authentication plugin in MySQL 8.0 
(https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html) ?

From my point of view there are two possible solutions:
- add mysql version (5.7) implicitly to avoid such problem
- try to migrate to mysql 8.0, but perhaps it will be needed to retest application

**Comment by vikasprogrammer** [comment]
> Hello @m4n3dw0lf @kingthorin @CSPF-Founder
> 
> I tried to use Docker feature but it does not work for me. It seems that it somehow connected to mysql version.
> 
> I've checked the repo and just executed "docker-compose up", then
> http://localhost:8080/JavaVulnerableLab/Install and click the Install Button, I've got following error in console log:
> 
> `javavulnlab_1 | SQLException: Could not create connection to database server. javavulnlab_1 | SQLState: 08001 javavulnlab_1 | VendorError: 0`
> and following message on web UI: "Something went wrong. Unable to install"
> 
> So I've changed mine docker-compose.yml from "image: mysql" to "image: mysql:5.7" and it works for me.
> 
> Could it be connected to new caching_sha2_password authentication plugin in MySQL 8.0
> (https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html) ?
> 
> From my point of view there are two possible solutions:
> 
> * add mysql version (5.7) implicitly to avoid such problem
> * try to migrate to mysql 8.0, but perhaps it will be needed to retest application

I am still getting the same problem even after changing to mysql:5.7

**Comment by vikasprogrammer** [comment]
@ GrigoriyLyullin
> * add mysql version (5.7) implicitly to avoid such problem

I am getting this error after changing mysql to mysql:5.7 in docker-compose.yml
```java.lang.NumberFormatException: For input string: "3306abc"```

**Comment by vikasprogrammer** [comment]
Ended up using ```jdbc:mysql://mysql:3306/``` to get this installed.

**Pull request merged**
